# Generated by Django 6.0.3 on 2026-03-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sps_lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название схемы')),
                ('background_image', models.ImageField(blank=True, help_text='Схема линии в формате PNG/SVG', null=True, upload_to='layouts/backgrounds/', verbose_name='Фоновое изображение (чертеж)')),
                ('width', models.IntegerField(default=1920, verbose_name='Ширина (px)')),
                ('height', models.IntegerField(default=1080, verbose_name='Высота (px)')),
                ('scale', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Масштаб')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='sps_lines.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Схема линии',
                'verbose_name_plural': 'Схемы линий',
            },
        ),
        migrations.CreateModel(
            name='ConnectionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('conveyor', 'Конвейер'), ('pipe', 'Трубопровод'), ('cable', 'Кабель'), ('mechanical', 'Механическая связь'), ('other', 'Другое')], default='conveyor', max_length=50, verbose_name='Тип соединения')),
                ('path_points', models.JSONField(blank=True, default=list, help_text='Координаты промежуточных точек', verbose_name='Точки пути')),
                ('color', models.CharField(default='#2196F3', max_length=20, verbose_name='Цвет линии')),
                ('line_width', models.IntegerField(default=3, verbose_name='Толщина линии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='sps_lines.node', verbose_name='От узла')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='sps_lines.node', verbose_name='До узла')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='sps_visualization.linelayout', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Соединение',
                'verbose_name_plural': 'Соединения',
                'ordering': ['layout', 'from_node'],
            },
        ),
        migrations.CreateModel(
            name='VisualizationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('settings', models.JSONField(default=dict, verbose_name='Настройки отображения')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='sps_visualization.linelayout', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Предустановка отображения',
                'verbose_name_plural': 'Предустановки отображения',
            },
        ),
        migrations.CreateModel(
            name='NodePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, help_text='Координата X на схеме', max_digits=8, verbose_name='Позиция X (px)')),
                ('y', models.DecimalField(decimal_places=2, help_text='Координата Y на схеме', max_digits=8, verbose_name='Позиция Y (px)')),
                ('width', models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='Ширина (px)')),
                ('height', models.DecimalField(decimal_places=2, default=60, max_digits=8, verbose_name='Высота (px)')),
                ('rotation', models.IntegerField(default=0, help_text='Угол поворота элемента', verbose_name='Поворот (градусы)')),
                ('z_index', models.IntegerField(default=1, help_text='Порядок наложения (больше = выше)', verbose_name='Слой Z')),
                ('icon', models.CharField(blank=True, help_text='CSS класс иконки или путь к изображению', max_length=100, verbose_name='Иконка')),
                ('color', models.CharField(default='#4CAF50', help_text='Цвет элемента (hex)', max_length=20, verbose_name='Цвет')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_positions', to='sps_visualization.linelayout', verbose_name='Схема')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='sps_lines.node', verbose_name='Узел')),
            ],
            options={
                'verbose_name': 'Позиция узла',
                'verbose_name_plural': 'Позиции узлов',
                'ordering': ['z_index', 'x', 'y'],
                'unique_together': {('layout', 'node')},
            },
        ),
    ]
