# Generated by Django 6.0.3 on 2026-04-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sps_lines', '0002_alter_line_inventory_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Изменение статуса'), ('node_error', 'Ошибка узла'), ('sensor_alert', 'Оповещение датчика'), ('maintenance', 'Обслуживание'), ('part_replace', 'Замена запчасти'), ('manual', 'Ручная запись'), ('system', 'Системное')], default='status_change', max_length=50, verbose_name='Тип события')),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('critical', 'Критично')], default='info', max_length=50, verbose_name='Важность')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время события')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные в JSON формате', verbose_name='Доп. данные')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sps_lines.line', verbose_name='Линия')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sps_lines.node', verbose_name='Узел')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sps_lines.sensor', verbose_name='Сенсор')),
                ('user', models.ForeignKey(blank=True, help_text='Создатель события', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': ('Событие',),
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sps_events__created_0f27ad_idx'), models.Index(fields=['line', '-created_at'], name='sps_events__line_id_4be870_idx'), models.Index(fields=['event_type'], name='sps_events__event_t_f98e19_idx'), models.Index(fields=['severity'], name='sps_events__severit_3492bb_idx')],
            },
        ),
    ]
