# Generated by Django 6.0.3 on 2026-03-30 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название линии')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('performance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Производительность (шт/час)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/lines', verbose_name='Фотография линии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('datetime_commissioning', models.DateTimeField(auto_now_add=True, verbose_name='Дата ввода в эксплуатацию')),
                ('datetime_decommissioning', models.DateTimeField(blank=True, null=True, verbose_name='Дата вывода из эксплуатации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['-datetime_commissioning'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('conveyor', 'Конвейер'), ('motor', 'Двигатель'), ('sensor_block', 'Блок датчиков'), ('controller', 'Контроллер'), ('actuator', 'Исполнительный механизм'), ('marking', 'Маркировка'), ('printer', 'Принтер'), ('other', 'Другое')], max_length=100, verbose_name='Тип узла')),
                ('name', models.CharField(max_length=200, verbose_name='Название узла')),
                ('inventory_number', models.CharField(blank=True, max_length=50, verbose_name='Инвентарный номер узла')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/nodes', verbose_name='Фотография узла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('datetime_service', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обслуживания')),
                ('service_interval_hours', models.IntegerField(default=0, help_text='Рекомендуемый интервал между обслуживаниями', verbose_name='Интервал обслуживания (часов)')),
                ('position_x', models.DecimalField(decimal_places=2, default=0, help_text='Позиция по горизонтали (0-100%)', max_digits=6, verbose_name='Позиция X (%)')),
                ('position_y', models.DecimalField(decimal_places=2, default=0, help_text='Позиция по вертикали (0-100%)', max_digits=6, verbose_name='Позиция Y (%)')),
                ('position_z', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Для 3D отображения', max_digits=6, null=True, verbose_name='Позиция Z (глубина)')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='sps_lines.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': 'Узлы',
                'ordering': ['line', 'position_x', 'position_y'],
                'unique_together': {('line', 'inventory_number')},
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Температура'), ('pressure', 'Давление'), ('vibration', 'Вибрация'), ('proximity', 'Приближения'), ('photoelectric', 'Фотоэлектрический'), ('encoder', 'Энкодер'), ('current', 'Ток'), ('voltage', 'Напряжение'), ('other', 'Другой')], max_length=100, verbose_name='Тип датчика')),
                ('name', models.CharField(max_length=200, verbose_name='Название датчика')),
                ('code', models.CharField(blank=True, help_text='Адрес в системе управления (например, I0.0, AIW16)', max_length=50, verbose_name='Код/адрес датчика')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/sensors', verbose_name='Фотография датчика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('unit_of_measurement', models.CharField(blank=True, help_text='°C, бар, мм/с, etc.', max_length=20, verbose_name='Единица измерения')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мин. значение')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. значение')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущее значение')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sps_lines.node', verbose_name='Узел')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'ordering': ['node', 'name'],
                'unique_together': {('node', 'code')},
            },
        ),
    ]
