# Generated by Django 6.0.3 on 2026-03-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sps_lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='node',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер узла'),
        ),
    ]
