# Generated by Django 6.0.3 on 2026-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sps_lines', '0002_alter_line_inventory_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_maintenance',
            field=models.BooleanField(default=False, verbose_name='Обслуживание'),
        ),
    ]
