# Generated by Django 6.0.3 on 2026-03-30 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sps_lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория запчасти',
                'verbose_name_plural': 'Категории запчастей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код склада')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название запчасти')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул/номер детали')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Производитель')),
                ('expected_lifetime_hours', models.IntegerField(default=0, help_text='Рекомендуемый срок службы в рабочих часах', verbose_name='Ожидаемый ресурс (часов)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parts/photos/', verbose_name='Фото запчасти')),
                ('documentation', models.FileField(blank=True, null=True, upload_to='parts/docs/', verbose_name='Документация (PDF)')),
                ('compatible_nodes', models.ManyToManyField(blank=True, help_text='Узлы, в которые может быть установлена эта деталь', related_name='compatible_parts', to='sps_lines.node', verbose_name='Совместимые узлы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='sps_parts.partcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата демонтажа')),
                ('installation_hours', models.IntegerField(default=0, help_text='Показания счетчика на момент установки', verbose_name='Наработка на момент установки (часов)')),
                ('current_hours', models.IntegerField(default=0, verbose_name='Текущая наработка (часов)')),
                ('installed_by', models.CharField(blank=True, max_length=100, verbose_name='Установил')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_installations', to='sps_lines.node', verbose_name='Узел')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='sps_parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Установка запчасти',
                'verbose_name_plural': 'Установки запчастей',
                'ordering': ['-installed_at'],
                'indexes': [models.Index(fields=['node', '-installed_at'], name='sps_parts_p_node_id_a5aed8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('supplier', models.CharField(max_length=200, verbose_name='Поставщик')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата доставки')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки')),
                ('status', models.CharField(choices=[('ordered', 'Заказан'), ('confirmed', 'Подтвержден'), ('shipped', 'Отгружен'), ('in_transit', 'В пути'), ('customs', 'На таможне'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='ordered', max_length=20, verbose_name='Статус')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за единицу')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Трекинг-номер')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sps_parts.part', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Заказ запчасти',
                'verbose_name_plural': 'Заказы запчастей',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['status', 'expected_delivery_date'], name='sps_parts_p_status_a69b39_idx')],
            },
        ),
        migrations.CreateModel(
            name='SparePartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('min_stock_level', models.IntegerField(default=1, help_text='При достижении этого количества нужно заказать', verbose_name='Минимальный запас')),
                ('location', models.CharField(blank=True, help_text='Ячейка/полка/стеллаж', max_length=100, verbose_name='Место на складе')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='sps_parts.part', verbose_name='Запчасть')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='sps_parts.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Запчасть на складе',
                'verbose_name_plural': 'Запчасти на складе',
                'ordering': ['warehouse', 'part'],
                'unique_together': {('part', 'warehouse')},
            },
        ),
    ]
